@startuml Network Sequence Diagram
    skinparam classAttributeIconSize 0
    participant Elevator1 #fd94dcff
    participant Elevator2 #fba29aff
    Elevator1->>Elevator1: init() on 1st floor
    activate Elevator1 #fd94dcff
    Elevator2->>Elevator2: init() on 3rd floor
    activate Elevator2 #fba29aff

    Elevator1->>Elevator1: hall button 4th floor pressed
    Elevator1->>Elevator2: broadcast WorldView
    Elevator2->>Elevator1: broadcast WorldView
    Elevator1->>Elevator2: broadcast WorldView

    Elevator2->>Elevator2: Request is assigned to Elevator2
    Elevator1->>Elevator1: Request is assigned to Elevator2

    alt Elevator2 services request
        Elevator2->>Elevator2: elevator moves to 4th floor
        Elevator2->>Elevator1: broadcast WorldView

    end
    alt Elevator2 dies on the way up
        Elevator2->>Elevator2: elevator moves to 4th floor
        Elevator2--x Elevator2: <color:red>(dies)</color>
        deactivate Elevator2
        Elevator1->>Elevator1: Network timeout, Elevator2 is marked dead
        Elevator1->>Elevator1: Assigner timeout
        Elevator1->>Elevator1: elevator moves to 4th floor

    end

    deactivate Elevator1
    deactivate Elevator2
@enduml
