@startuml Thread Handle Request Sequence Diagram
    participant Network #9efe9eff
    participant Assigner #LightBlue
    participant ElevatorControl #FFE5B4

    Network->>Network:init()
    activate Network #9efe9eff
    Assigner->>Assigner:init()
    activate Assigner #LightBlue
    ElevatorControl->>ElevatorControl:init() 
    activate ElevatorControl #FFE5B4
    Network->>Network: Receive initial WorldView
    Network->>ElevatorControl: Send initial WorldView

    loop Regular loop
    ElevatorControl->>Network: Update WorldView (update requests)
    Network->>Network: Broadcast WorldView to Network
    Network->>Network: Make sure WorldView is coherent among nodes
    Network->>Assigner: Send WorldView
    Network->>ElevatorControl: Send WorldView
    ElevatorControl->>ElevatorControl: Service lights

    Assigner->>Assigner: Calculate best assignment
    Assigner->>ElevatorControl: Share best assignment
    ElevatorControl->>ElevatorControl: Service assignment
    ElevatorControl->>Network: Update WorldView (update serviced)
    end

    alt Network timeout
    ElevatorControl->>Network: Update WorldView (update requests)
    Network->>Network: Broadcast WorldView to Network 
    Network--x Network: Make sure WorldView is coherent among nodes <color:red>(failed)</color>


    Assigner->>Assigner: Network timeout
    Assigner->>Assigner: Go inactive
    ElevatorControl->>ElevatorControl: Assigner timeout
    ElevatorControl->>ElevatorControl: Activate local control
    ElevatorControl->>ElevatorControl: Service assignment
    ElevatorControl->>Network: Update WorldView (update serviced)
    end

    deactivate Network
    deactivate Assigner
    deactivate ElevatorControl
@enduml